apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- todo_app/manifests/statefulset.yaml
- todo_app/manifests/deployment.yaml
- todo_app/manifests/deployment-backend.yaml
- todo_app/manifests/service.yaml
- todo_app/manifests/service-backend.yaml
- todo_app/manifests/cronjob.yaml
# - todo_app/manifests/ingress.yaml
images:
- name: PROJECT/FRONTEND
  newName: pavelgar/todo_app:latest
- name: PROJECT/BACKEND
  newName: pavelgar/todo_app-backend:latest
