apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- manifests/deployment.yaml
- manifests/deployment-backend.yaml
- manifests/service.yaml
- manifests/service-backend.yaml
images:
- name: PROJECT/FRONTEND
  newName: pavelgar/todo_app:latest
- name: PROJECT/BACKEND
  newName: pavelgar/todo_app-backend:latest
