apiVersion: apps/v1
kind: Deployment
metadata:
  name: ping-dep
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ping-pong
  template:
    metadata:
      labels:
        app: ping-pong
    spec:
      volumes: # Define volume
        - name: shared-hash
          persistentVolumeClaim:
            claimName: hashlogger-claim

      containers:
        - name: ping-pong
          image: pavelgar/ping-pong:latest
          volumeMounts: # Mount volume
            - name: shared-hash
              mountPath: /usr/src/app/files
