apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: main-application
  name: ping-dep
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ping-pong
  template:
    metadata:
      labels:
        app: ping-pong
    spec:
      containers:
        - name: ping-pong
          image: pavelgar/ping-pong:latest
          resources:
            limits:
              cpu: "100m"
              memory: "100Mi"
          envFrom:
            - secretRef:
                name: postgres-pass
