apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: main-application
  name: ping-dep
spec:
  replicas: 4
  selector:
    matchLabels:
      app: ping-pong
  template:
    metadata:
      labels:
        app: ping-pong
    spec:
      containers:
        - name: ping-pong
          image: pavelgar/ping-pong:latest
          readinessProbe:
            initialDelaySeconds: 10 # Initial delay until the readiness is tested
            periodSeconds: 5 # How often to test
            httpGet:
               path: /healthz
               port: 3000
          resources:
            limits:
              cpu: "100m"
              memory: "100Mi"
          envFrom:
            - secretRef:
                name: postgres-pass
