apiVersion: v1
kind: Service
metadata:
  namespace: main-application
  name: ping-service
spec:
  type: ClusterIP
  selector:
    app: ping-pong
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: 3000
