apiVersion: v1
kind: Service
metadata:
  namespace: main-application
  name: ping-svc
spec:
  type: NodePort
  selector:
    app: ping-pong
  ports:
    - port: 80
      protocol: TCP
      targetPort: 3000
