apiVersion: argoproj.io/v1alpha1
kind: AnalysisTemplate
metadata:
  namespace: todo-application
  name: cpu-usage
spec:
  metrics:
  - name: cpu-usage
    initialDelay: 10m
    successCondition: result < 0.1
    provider:
      prometheus:
        address: http://kube-prometheus-stack-1626-prometheus.prometheus.svc.cluster.local:9090
        query: scalar(sum(node_namespace_pod_container:container_cpu_usage_seconds_total:sum_irate{namespace="todo-application"}) > 0.00001)
