apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: todo-application
  name: todo-broadcaster-dep
spec:
  replicas: 6
  selector:
    matchLabels:
      app: broadcaster
  template:
    metadata:
      labels:
        app: broadcaster
    spec:
      containers:
        - name: broadcaster
          image: BROADCASTER_IMAGE
          env:
            - name: NATS_URL
              value: nats://my-nats.default:4222
            - name: GENERIC_URL
              value: example.com/api
---
apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: todo-application
  name: todo-backend-dep
spec:
  replicas: 1
  selector:
    matchLabels:
      app: todo-backend
  template:
    metadata:
      labels:
        app: todo-backend
    spec:
      containers:
        - name: todo-backend
          image: BACKEND_IMAGE
          envFrom:
            - secretRef:
                name: todo-postgres-pass
          env:
            - name: NATS_URL
              value: nats://my-nats.default:4222
---
apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: todo-application
  name: todo-frontend-dep
spec:
  replicas: 1
  selector:
    matchLabels:
      app: todo-frontend
  template:
    metadata:
      labels:
        app: todo-frontend
    spec:
      containers:
        - name: todo-frontend
          image: FRONTEND_IMAGE
---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: monitoring-nats
  namespace: prometheus
  labels:
    release: kube-prometheus-stack-1626019742
spec:
  selector:
    matchLabels:
      app: my-nats
  endpoints:
    - interval: 10s
      path: /metrics
      port: metrics
  namespaceSelector:
    matchNames:
      - default
