apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: todo-application
  name: todo-app-backend-dep
spec:
  replicas: 1
  selector:
    matchLabels:
      app: todo-app-backend
  template:
    metadata:
      labels:
        app: todo-app-backend
    spec:
      containers:
        - name: todo-app-backend
          image: PROJECT/BACKEND
          resources:
            limits:
              cpu: "100m"
              memory: "100Mi"
          envFrom:
            - secretRef:
                name: todo-postgres-pass
          readinessProbe:
            initialDelaySeconds: 10 # Initial delay until the readiness is tested
            periodSeconds: 5 # How often to test
            httpGet:
               path: /
               port: 3000
          livenessProbe:
            initialDelaySeconds: 30 # Initial delay until the liveness is tested
            periodSeconds: 5 # How often to test
            httpGet:
               path: /
               port: 3000
