apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: todo-application
  name: todo-app-backend-dep
spec:
  replicas: 1
  selector:
    matchLabels:
      app: todo-app-backend
  template:
    metadata:
      labels:
        app: todo-app-backend
    spec:
      containers:
        - name: todo-app-backend
          image: pavelgar/todo_app-backend:latest
          envFrom:
            - secretRef:
                name: todo-postgres-pass
