apiVersion: apps/v1
kind: Deployment
metadata:
  name: todo_app-dep
spec:
  replicas: 1
  selector:
    matchLabels:
      app: todo_app
  template:
    metadata:
      labels:
        app: todo_app
    spec:
      containers:
        - name: todo_app
          image: pavelgar/todo_app:latest
