apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  namespace: todo-application
  name: todo-app-hpa
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: todo-app-dep
  minReplicas: 1
  maxReplicas: 6
  targetCPUUtilizationPercentage: 25
