apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  namespace: todo-application
  name: todo-app-ingress
  annotations:
    traefik.ingress.kubernetes.io/rule-type: "PathPrefixStrip"
spec:
  rules:
  - http:
      paths:
      - path: /
        backend:
          serviceName: todo-app-svc
          servicePort: 1234
      - path: /api
        backend:
          serviceName: todo-app-backend-svc
          servicePort: 3456
