apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- sealedsecret.yaml
- statefulset.yaml
- deployment-nats.yaml
- service-nats.yaml
- ingress.yaml
- cronjob.yaml
images:
- name: BACKEND_IMAGE
  newName: pavelgar/todo_app-backend
  newTag: e4ed5634d2bdfa5f3188f181501daf1cb67f36dc
- name: BROADCASTER_IMAGE
  newName: pavelgar/todo_app-broadcaster
  newTag: e4ed5634d2bdfa5f3188f181501daf1cb67f36dc
- name: FRONTEND_IMAGE
  newName: pavelgar/todo_app
  newTag: e4ed5634d2bdfa5f3188f181501daf1cb67f36dc
