apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- sealedsecret.yaml
- statefulset.yaml
- deployment-nats.yaml
- service-nats.yaml
- ingress.yaml
- cronjob.yaml
images:
- name: BACKEND_IMAGE
  newName: pavelgar/todo_app-backend
  newTag: 4353a48310f400a81dccebfab67bcf5abb66009d
- name: BROADCASTER_IMAGE
  newName: pavelgar/todo_app-broadcaster
  newTag: 4353a48310f400a81dccebfab67bcf5abb66009d
- name: FRONTEND_IMAGE
  newName: pavelgar/todo_app
  newTag: 4353a48310f400a81dccebfab67bcf5abb66009d
