apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: postgres-pass
  namespace: todo-application
spec:
  encryptedData:
    POSTGRES_PASSWORD: AgCKwcwqMZuf3G7FxbNDo3/PZdYcoCnWV4F0Ksiup6DJauDQBVMCTOPzgtUhsspqcaBFEVWHz7A7n2Tng8pwLS/K2bWaJpLeRSn5eohBFarpBHyFGqi9U9h3l4YUEsBN2VwjeLmkrp1tNuwOSHlj5RehKfuA+X7Be0wO2/R7GEnjR2MttM2TAGXCQEpgtcJygDmC1u4MS7th/DrLcRnCd49lqU752l2qZJpf/SxfJDkm2DwVMJe3j8UDOTlj7aaWIEpKhvIwkVUa4YBZA4HBcBabqdrNBj9EsuObX0Yd93Atl35D5b2y7SQiRRwA2siMvRmGyZ3YjCEfsL05FQpKt45bqGJhs2gpS1JUjsGRX68W1+q260GK2czPRwBuxzZ0NFIXsJK7Nf4pQ4iiIT6rrRia7mXZ19VonmZ9tEYHJaIh+WuL/FrD6i/BXiU7ftFN+fRFlTXSfxRUAVzEqy5KpNBxRh+PVb2c/QJ3mnF95rFRa5FjjlTfnH9FMijviddn4REmC4oKhGD7yuZp+xUb3ph15L5EQajzwJCRSuwL7iLLWfxv9r1KrDHHHDZitc0drSmVhgXLwg2F55s/h9GRsUvXwqoaTSsyoLOJfCYJUhXGprsZkB2y9m0t0RpVQRo4bC7J22QI6J1aWnzjw4Q3FFaOddzppXyV7x8TY4MK70e5a5uoInTmrg7vP08zQB37KAZ+dgf/v0Rj92KZDM2eY+ZmCpbpOBmw
  template:
    data: null
    metadata:
      creationTimestamp: null
      name: postgres-pass
      namespace: todo-application
