name: Release app using gitops

on:
  push:
    branches:
      - master
    paths:
      - 'todo_app/**'
      - '.github/workflows/gitops.yml'

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    # Build and push
    - name: Publish frontend to Registry
      uses: docker/build-push-action@v1
      with:
        repository: pavelgar/todo_app
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
        tags: ${{ github.sha }}
        path: todo_app/frontend/

    - name: Publish backend to Registry
      uses: docker/build-push-action@v1
      with:
        repository: pavelgar/todo_app-backend
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
        tags: ${{ github.sha }}
        path: todo_app/backend/

    - name: Publish broadcaster to Registry
      uses: docker/build-push-action@v1
      with:
        repository: pavelgar/todo_app-broadcaster
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
        tags: ${{ github.sha }}
        path: todo_app/broadcaster/

  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    needs: build

    steps:
    - uses: actions/checkout@v2

    - name: Set up Kustomize
      working-directory: todo_app/manifests
      run: |-
        curl -sfLo kustomize https://github.com/kubernetes-sigs/kustomize/releases/download/v3.1.0/kustomize_3.1.0_linux_amd64
        chmod u+x ./kustomize

    # Update yamls
    - name: Update yamls
      working-directory: todo_app/manifests
      run: |-
        ./kustomize edit set image FRONTEND_IMAGE=pavelgar/todo_app:${{ github.sha }}
        ./kustomize edit set image BACKEND_IMAGE=pavelgar/todo_app-backend:${{ github.sha }}
        ./kustomize edit set image BROADCASTER_IMAGE=pavelgar/todo_app-broadcaster:${{ github.sha }}

    # Commit and push
    - uses: EndBug/add-and-commit@v5
      with:
        add: 'todo_app/manifests/kustomization.yaml'
        message: New version release for todo_app ${{ github.sha }}
      env:
        GITHUB_TOKEN: ${{ secrets._GITHUB_TOKEN }}
