apiVersion: apps/v1
kind: Deployment
metadata:
  name: hashlogger-dep
spec:
  replicas: 1
  selector:
    matchLabels:
      app: hashlogger
  template:
    metadata:
      labels:
        app: hashlogger
    spec:
      volumes: # Define volume
        - name: shared-hash
          persistentVolumeClaim:
            claimName: hashlogger-claim

      containers:
        - name: hashlogger-backend
          image: pavelgar/hashlogger-backend:latest
          volumeMounts: # Mount volume
            - name: shared-hash
              mountPath: /usr/src/app/files

        - name: hashlogger-frontend
          image: pavelgar/hashlogger-frontend:latest
          volumeMounts: # Mount volume
            - name: shared-hash
              mountPath: /usr/src/app/files
