apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  namespace: main-application
  name: hashlogger-hpa
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: hashlogger-dep
  minReplicas: 1
  maxReplicas: 6
  targetCPUUtilizationPercentage: 35
