apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: hashlogger-ingress
spec:
  rules:
  - http:
      paths:
      - path: /
        backend:
          serviceName: hashlogger-svc
          servicePort: 2345
