apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  namespace: main-application
  name: hashlogger-claim
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
